apiVersion: 1
# Route all appchain alerts to Slack.
policies:
  - orgId: 1
    receiver: slack
    group_by: ['alertname', 'deployment']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
